{
    function fun() {
        return "123";
    }
}

console.log(fun); //no error as funtion doesnot follow block scope
